config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'

  resources :rooms, only: %i[create index show destroy], param: :token

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  before_create :generate_token

  belongs_to :user
  has_many :messages, dependent: :destroy

  def to_param
    token
  end

  private

  def generate_token
    self.token = SecureRandom.hex(2)
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_create :generate_nickname

  has_many :rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  private

  def generate_nickname
    self.nickname = Faker::Name.first_name.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.where(id: cookies.signed[:user_id]).first

    if @current_user.nil?
      @current_user = User.create
      cookies.signed[:user_id] = current_user.id
    end

    @current_user
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[show destroy]

  def index
    @rooms = Room.all
    @room = Room.new
  end

  def show; end

  def create
    @room = Room.create!(user_id: current_user.id)

    redirect_to @room, notice: 'Room was successfully created.'
  end

  def destroy
    if @room.user_id == current_user.id
      @room.destroy

      redirect_to root_path, notice: 'Room was successfully deleted.'
    end
  end

  private

  def set_room
    @room = Room.find_by(token: params[:token])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatroom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col-md-8">
          <div class="card text-center mt-4 mb-4">
            <div class="card-body">
              Welcome to ChatRoom, <b><%= current_user.nickname %></b>!
              <hr>
              <ul id="user-list" class="mt-4 list-unstyled">
                Now online
                <%= render partial: 'users/user', collection: @users %>
              </ul>
            </div>
          </div>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<div class="mt-2">
  <%= form_tag do |f| %>
    <div class="form-group">
      <div class="input-group">
        <%= text_field_tag :message_body, '', class: 'form-control',
          placeholder: 'Enter message' %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/_message.html.erb
<div class="row message mt-1">
  <div class="col-2 font-weight-bold text-info">
    <%= message.user.nickname %>
  </div>
  <div class="col-10">
    <div class="float-end small badge bg-info">
      <%= message.created_at.strftime("%H:%M") %>
    </div>
    <div><%= message.body %></div>
  </div>
</div>

app/views/rooms/_form.html.erb
<%= form_for @room do |form| %>
  <div class="actions">
    <%= form.submit 'Create Room', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<li><b>Room #<%= room.id %></b> — <%= link_to 'Join', room, class: "button btn btn-primary" %></li>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Rooms</h1>
<ul class="mt-4 list-unstyled">
  <%= render @rooms %>
</ul>
<div class="mt-2">
  <%= render 'rooms/form', room: @room %>
</div>

app/views/rooms/show.html.erb
<h1>Room <%= @room.id %></h1>
<%= link_to "Leave", root_path, class: "button btn btn-primary", data: { turbolinks: false } %>
<% if current_user == @room.user %>
  <%= link_to "Delete room", room_path(@room.token), class: "button btn btn-danger",
      method: :delete, data: { confirm: "Are you sure you want to delete the room?" } %>
<% end %>
<p id="notice"><%= notice %></p>
<div class="messages">
  <div class="messages-inner" id="messages" data-room-id="<%= @room.id %>">
    <%= render @room.messages %>
  </div>
</div>
<%= render 'messages/form' %>

app/views/users/_user.html.erb
<% if user.status %>
  <li data-user-id="<%= user.id %>" data-user-status="<%= user.status %>">
    <b><%= user.nickname %></b>
    <span class="spinner-grow text-success">&#183;</span>
  </li>
<% end %>